//go:build windows

// Windows apply helper: a detached .cmd waits for the app to exit, replaces
// the executable, relaunches it, and deletes itself.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
)

func writeApplyScript(downloadedPath, executable string) (string, error) {
	scriptFile, err := os.CreateTemp(os.TempDir(), "mncode-apply-update-*.cmd")
	if err != nil { return "", err }
	scriptPath := scriptFile.Name()
	if err := scriptFile.Chmod(0600); err != nil { _ = scriptFile.Close(); _ = os.Remove(scriptPath); return "", err }
	staging := filepath.Join(os.TempDir(), "mncode-update-"+filepath.Base(scriptPath))
	payload := filepath.Join(staging, filepath.Base(executable))
	backup := executable + ".mncode-backup-" + filepath.Base(scriptPath)
	// Paths are generated by the OS and the executable path is resolved by
	// os.Executable; quote and escape command metacharacters before writing.
	script := fmt.Sprintf(`@echo off
setlocal DisableDelayedExpansion
timeout /t 2 /nobreak >nul
set "MNCODE_UPDATE_ARCHIVE=%s"
set "MNCODE_UPDATE_STAGING=%s"
set "MNCODE_UPDATE_PAYLOAD=%s"
set "MNCODE_UPDATE_BACKUP=%s"
mkdir "%%MNCODE_UPDATE_STAGING%%" >nul 2>&1
if errorlevel 1 goto :cleanup_failed
powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command "$ErrorActionPreference='Stop'; Expand-Archive -LiteralPath $env:MNCODE_UPDATE_ARCHIVE -DestinationPath $env:MNCODE_UPDATE_STAGING -Force"
if errorlevel 1 goto :cleanup_failed
if not exist "%%MNCODE_UPDATE_PAYLOAD%%" goto :cleanup_failed
copy /Y %s "%%MNCODE_UPDATE_BACKUP%%" >nul
if errorlevel 1 goto :cleanup_failed
copy /Y "%%MNCODE_UPDATE_PAYLOAD%%" %s >nul
if errorlevel 1 goto :restore_failed
start "" %s
if errorlevel 1 goto :restore_failed
del /f /q "%%MNCODE_UPDATE_BACKUP%%" >nul 2>&1
rmdir /S /Q "%%MNCODE_UPDATE_STAGING%%" >nul 2>&1
del /f /q %s >nul 2>&1
del "%%~f0"
exit /b 0
:restore_failed
copy /Y "%%MNCODE_UPDATE_BACKUP%%" %s >nul
del /f /q "%%MNCODE_UPDATE_BACKUP%%" >nul 2>&1
rmdir /S /Q "%%MNCODE_UPDATE_STAGING%%" >nul 2>&1
del /f /q %s >nul 2>&1
del "%%~f0"
exit /b 1
`, batchEscape(downloadedPath), batchEscape(staging), batchEscape(payload), batchEscape(backup), batchQuote(executable), batchQuote(executable), batchQuote(executable), batchQuote(downloadedPath), batchQuote(downloadedPath), batchQuote(executable))
	if _, err := scriptFile.WriteString(script); err != nil { _ = scriptFile.Close(); _ = os.Remove(scriptPath); return "", err }
	if err := scriptFile.Close(); err != nil { _ = os.Remove(scriptPath); return "", err }
	return scriptPath, nil
}

func batchEscape(value string) string {
	return strings.NewReplacer("^", "^^", "&", "^&", "|", "^|", "<", "^<", ">", "^>", "%", "%%", "!", "^!").Replace(value)
}

func batchQuote(value string) string {
	return `"` + batchEscape(value) + `"`
}

func spawnDetached(scriptPath string) error {
	cmd := exec.Command(filepath.Join(os.Getenv("WINDIR"), "System32", "cmd.exe"), "/D", "/Q", "/C", scriptPath)
	cmd.SysProcAttr = &syscall.SysProcAttr{HideWindow: true, CreationFlags: 0x00000008 | 0x00000200}
	return cmd.Start()
}
