import { useCallback, useEffect, useMemo, useState } from "react";
import { Check, Download, ExternalLink, PackageOpen, RefreshCw, Search, ShieldCheck, Sparkles, Trash2 } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { DesktopSkill, DesktopSkillsMarketplace } from "@/types";

type MarketplaceTab = "discover" | "installed";

export function SkillsMarketplace({ onLoad, onInstall, onDelete, onOpenURL }: { onLoad: () => Promise<DesktopSkillsMarketplace>; onInstall: (slug: string) => Promise<DesktopSkill>; onDelete: (id: string) => Promise<void>; onOpenURL: (url: string) => void }) {
  const [data, setData] = useState<DesktopSkillsMarketplace>();
  const [tab, setTab] = useState<MarketplaceTab>("discover");
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(true);
  const [busySlug, setBusySlug] = useState("");
  const [deleteTarget, setDeleteTarget] = useState<DesktopSkill>();
  const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await onLoad()); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load skills"); } finally { setLoading(false); } }, [onLoad]);
  useEffect(() => { void load(); }, [load]);
  const filtered = useMemo(() => (data?.availableSkills ?? []).filter((skill) => `${skill.name} ${skill.description} ${skill.category}`.toLowerCase().includes(query.toLowerCase().trim())), [data, query]);
  async function install(skill: DesktopSkill) { setBusySlug(skill.slug); setError(""); try { await onInstall(skill.slug); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not install skill"); } finally { setBusySlug(""); } }
  async function remove() { if (!deleteTarget) return; setBusySlug(deleteTarget.id); try { await onDelete(deleteTarget.id); setDeleteTarget(undefined); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not delete skill"); } finally { setBusySlug(""); } }
  if (loading && !data) return <div className="mt-8 space-y-3"><div className="h-28 animate-pulse rounded-xl bg-[var(--mn-surface-muted)]" /><div className="h-44 animate-pulse rounded-xl bg-[var(--mn-surface-muted)]" /></div>;
  return <div className="mt-8 space-y-5">
    {error && <div className="rounded-xl border border-rose-500/25 bg-rose-500/8 px-4 py-3 text-xs text-rose-700 dark:text-rose-200">{error}</div>}
    <Card className="mn-surface shadow-none"><CardContent className="flex flex-wrap items-center gap-3 p-4"><div className="grid size-10 place-items-center rounded-xl bg-[var(--mn-accent-soft)] text-[var(--mn-accent-strong)]"><Sparkles className="size-5" /></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">Extend the agent surface</p><p className="mt-1 text-xs text-muted-foreground">Install free community skills into the shared mncode skill directory.</p></div><Button variant="outline" size="sm" onClick={() => onOpenURL(data?.sourceUrl || "https://mcpmarket.com/tools/skills/all")} className="border-[var(--mn-line)]"><ExternalLink className="mr-2 size-3.5" />Open MCP Market</Button></CardContent></Card>
    <div className="flex flex-wrap items-center gap-2"><div className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search free skills..." className="h-10 border-[var(--mn-line)] bg-[var(--mn-surface)] pl-9" /></div><div className="flex rounded-lg bg-[var(--mn-surface-muted)] p-1"><button type="button" onClick={() => setTab("discover")} className={`rounded-md px-3 py-1.5 text-xs ${tab === "discover" ? "bg-[var(--mn-surface)] font-medium shadow-sm" : "text-muted-foreground"}`}>Discover</button><button type="button" onClick={() => setTab("installed")} className={`rounded-md px-3 py-1.5 text-xs ${tab === "installed" ? "bg-[var(--mn-surface)] font-medium shadow-sm" : "text-muted-foreground"}`}>Installed</button></div><Button variant="ghost" size="icon-sm" onClick={() => void load()} disabled={loading} aria-label="Refresh skills"><RefreshCw className={`size-4 ${loading ? "animate-spin" : ""}`} /></Button></div>
    {tab === "discover" ? <section><div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="text-sm font-semibold">Free from MCP Market</h2><p className="mt-1 text-xs text-muted-foreground">Curated open-source entries. Review each SKILL.md before enabling it.</p></div><span className="font-mono text-[10px] text-muted-foreground">{filtered.length} skills</span></div><div className="grid gap-3 lg:grid-cols-2">{filtered.map((skill) => <SkillCard key={skill.slug} skill={skill} busy={busySlug === skill.slug} onInstall={() => void install(skill)} onOpen={() => onOpenURL(skill.marketplaceUrl)} />)}</div>{filtered.length === 0 && <EmptySkills text="No matching skills." />}</section> : <section className="space-y-6"><InstalledGroup title="System skills" description="Provided by the local agent environment. These cannot be deleted." skills={data?.systemSkills ?? []} busySlug={busySlug} onDelete={() => undefined} /><InstalledGroup title="Your installed skills" description="Installed into ~/.mncode/skills and shared with the CLI." skills={data?.userSkills ?? []} busySlug={busySlug} onDelete={setDeleteTarget} /></section>}
    <div className="flex items-start gap-2 rounded-xl border border-[var(--mn-line)] bg-[var(--mn-surface-muted)] px-4 py-3 text-xs leading-5 text-muted-foreground"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-[var(--mn-accent-strong)]" />Skills are instruction files. Install only sources you trust and inspect their contents before using them in agent turns.</div>
    <Dialog open={Boolean(deleteTarget)} onOpenChange={(open) => { if (!open) setDeleteTarget(undefined); }}><DialogContent className="border-[var(--mn-line)] bg-[var(--mn-surface)] text-foreground"><DialogHeader><DialogTitle>Delete installed skill?</DialogTitle><DialogDescription>Remove “{deleteTarget?.name}” from the shared mncode skill directory. System skills are protected.</DialogDescription></DialogHeader><DialogFooter><Button variant="ghost" onClick={() => setDeleteTarget(undefined)}>Cancel</Button><Button variant="destructive" disabled={Boolean(busySlug)} onClick={() => void remove()}><Trash2 className="mr-2 size-3.5" />Delete skill</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}

function SkillCard({ skill, busy, onInstall, onOpen }: { skill: DesktopSkill; busy: boolean; onInstall: () => void; onOpen: () => void }) { return <Card className="mn-surface shadow-none transition-colors hover:border-[var(--mn-accent)]/45"><CardContent className="flex min-h-40 flex-col p-4"><div className="flex items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-[var(--mn-surface-muted)] text-[var(--mn-accent-strong)]"><PackageOpen className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="truncate text-sm font-semibold">{skill.name}</h3><Badge variant="outline" className="border-emerald-500/25 bg-emerald-500/8 text-[9px] text-emerald-700 dark:text-emerald-300">Free</Badge></div><p className="mt-1 line-clamp-3 text-xs leading-5 text-muted-foreground">{skill.description}</p></div></div><div className="mt-auto flex items-center gap-2 pt-4"><span className="truncate text-[10px] text-muted-foreground">{skill.category}</span><Button variant="ghost" size="icon-xs" onClick={onOpen} className="ml-auto" aria-label={`Open ${skill.name} on MCP Market`}><ExternalLink className="size-3.5" /></Button>{skill.installed ? <Button size="sm" variant="outline" disabled className="border-[var(--mn-line)]"><Check className="mr-2 size-3.5" />Installed</Button> : <Button size="sm" onClick={onInstall} disabled={busy} className="mn-accent-button">{busy ? <RefreshCw className="mr-2 size-3.5 animate-spin" /> : <Download className="mr-2 size-3.5" />}{busy ? "Installing..." : "Install"}</Button>}</div></CardContent></Card>; }

function InstalledGroup({ title, description, skills, busySlug, onDelete }: { title: string; description: string; skills: DesktopSkill[]; busySlug: string; onDelete: (skill: DesktopSkill) => void }) { return <section><div className="mb-3"><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{description}</p></div>{skills.length === 0 ? <EmptySkills text="No skills in this group." /> : <div className="space-y-2">{skills.map((skill) => <div key={skill.id} className="flex items-center gap-3 rounded-xl border border-[var(--mn-line)] bg-[var(--mn-surface)] px-3 py-2.5"><div className="grid size-7 shrink-0 place-items-center rounded-md bg-[var(--mn-surface-muted)] text-[var(--mn-accent-strong)]"><PackageOpen className="size-3.5" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold">{skill.name}</p><p className="truncate text-[10px] text-muted-foreground">{skill.description}</p></div>{skill.system ? <Badge variant="outline" className="border-[var(--mn-line)] text-[9px]">System</Badge> : <Button variant="ghost" size="icon-xs" disabled={busySlug === skill.id} onClick={() => onDelete(skill)} aria-label={`Delete ${skill.name}`} className="text-rose-600 hover:text-rose-700"><Trash2 className="size-3.5" /></Button>}</div>)}</div>}</section>; }

function EmptySkills({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-[var(--mn-line)] px-4 py-8 text-center text-xs text-muted-foreground">{text}</div>; }
