// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnswerQuestion(arg1, arg2) {
  return window['go']['main']['App']['AnswerQuestion'](arg1, arg2);
}

export function ApplyUpdateAndRestart(arg1) {
  return window['go']['main']['App']['ApplyUpdateAndRestart'](arg1);
}

export function CancelTurn() {
  return window['go']['main']['App']['CancelTurn']();
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckRtkInstalled() {
  return window['go']['main']['App']['CheckRtkInstalled']();
}

export function ChooseAttachment() {
  return window['go']['main']['App']['ChooseAttachment']();
}

export function ChooseWorkspace() {
  return window['go']['main']['App']['ChooseWorkspace']();
}

export function CloseTerminal() {
  return window['go']['main']['App']['CloseTerminal']();
}

export function ConfigureMCPServer(arg1) {
  return window['go']['main']['App']['ConfigureMCPServer'](arg1);
}

export function ConfigureOpenCode(arg1) {
  return window['go']['main']['App']['ConfigureOpenCode'](arg1);
}

export function ConfigureProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfigureProvider'](arg1, arg2, arg3);
}

export function CreateAutomation(arg1) {
  return window['go']['main']['App']['CreateAutomation'](arg1);
}

export function DeleteAutomation(arg1) {
  return window['go']['main']['App']['DeleteAutomation'](arg1);
}

export function DeleteCustomProvider(arg1) {
  return window['go']['main']['App']['DeleteCustomProvider'](arg1);
}

export function DeleteInstalledSkill(arg1) {
  return window['go']['main']['App']['DeleteInstalledSkill'](arg1);
}

export function DeleteLocalMemories() {
  return window['go']['main']['App']['DeleteLocalMemories']();
}

export function DownloadUpdate(arg1) {
  return window['go']['main']['App']['DownloadUpdate'](arg1);
}

export function GetAccount() {
  return window['go']['main']['App']['GetAccount']();
}

export function GetActiveAntigravityQuota() {
  return window['go']['main']['App']['GetActiveAntigravityQuota']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetBrowserSettings() {
  return window['go']['main']['App']['GetBrowserSettings']();
}

export function GetCatalog() {
  return window['go']['main']['App']['GetCatalog']();
}

export function GetKeepAwake() {
  return window['go']['main']['App']['GetKeepAwake']();
}

export function GetMCPServers() {
  return window['go']['main']['App']['GetMCPServers']();
}

export function GetPersonalization() {
  return window['go']['main']['App']['GetPersonalization']();
}

export function GetProviderSettings() {
  return window['go']['main']['App']['GetProviderSettings']();
}

export function GetRemoteSession() {
  return window['go']['main']['App']['GetRemoteSession']();
}

export function GetSkillsMarketplace() {
  return window['go']['main']['App']['GetSkillsMarketplace']();
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function GetWorkspace() {
  return window['go']['main']['App']['GetWorkspace']();
}

export function InstallMarketplaceSkill(arg1) {
  return window['go']['main']['App']['InstallMarketplaceSkill'](arg1);
}

export function InterruptTerminal() {
  return window['go']['main']['App']['InterruptTerminal']();
}

export function ListAutomations() {
  return window['go']['main']['App']['ListAutomations']();
}

export function ListWorkspaceTree() {
  return window['go']['main']['App']['ListWorkspaceTree']();
}

export function LoginAccount() {
  return window['go']['main']['App']['LoginAccount']();
}

export function LoginProvider(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginProvider'](arg1, arg2, arg3);
}

export function LogoutAccount() {
  return window['go']['main']['App']['LogoutAccount']();
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenStandaloneChat() {
  return window['go']['main']['App']['OpenStandaloneChat']();
}

export function OpenTerminal() {
  return window['go']['main']['App']['OpenTerminal']();
}

export function OpenUpdatePage(arg1) {
  return window['go']['main']['App']['OpenUpdatePage'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function ReadAutomationLog(arg1) {
  return window['go']['main']['App']['ReadAutomationLog'](arg1);
}

export function ResolvePermission(arg1, arg2) {
  return window['go']['main']['App']['ResolvePermission'](arg1, arg2);
}

export function RunAutomationNow(arg1) {
  return window['go']['main']['App']['RunAutomationNow'](arg1);
}

export function RunTerminalCommand(arg1) {
  return window['go']['main']['App']['RunTerminalCommand'](arg1);
}

export function SaveCustomProvider(arg1) {
  return window['go']['main']['App']['SaveCustomProvider'](arg1);
}

export function SavePersonalization(arg1) {
  return window['go']['main']['App']['SavePersonalization'](arg1);
}

export function SendPrompt(arg1) {
  return window['go']['main']['App']['SendPrompt'](arg1);
}

export function SetKeepAwake(arg1) {
  return window['go']['main']['App']['SetKeepAwake'](arg1);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function StartRemoteSession() {
  return window['go']['main']['App']['StartRemoteSession']();
}

export function SteerPrompt(arg1) {
  return window['go']['main']['App']['SteerPrompt'](arg1);
}

export function StopRemoteSession() {
  return window['go']['main']['App']['StopRemoteSession']();
}

export function ToggleAutomation(arg1, arg2) {
  return window['go']['main']['App']['ToggleAutomation'](arg1, arg2);
}

export function UpdateAutomation(arg1, arg2) {
  return window['go']['main']['App']['UpdateAutomation'](arg1, arg2);
}

export function UpdateBrowserSettings(arg1) {
  return window['go']['main']['App']['UpdateBrowserSettings'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UseProviderAccount(arg1) {
  return window['go']['main']['App']['UseProviderAccount'](arg1);
}
