// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {skills} from '../models';

export function AnswerQuestion(arg1:string,arg2:string):Promise<void>;

export function ApplyUpdateAndRestart(arg1:string):Promise<void>;

export function CancelTurn():Promise<void>;

export function CheckForUpdate():Promise<main.DesktopUpdateInfo>;

export function CheckHeadroomInstalled():Promise<boolean>;

export function CheckRtkInstalled():Promise<boolean>;

export function ChooseAttachment():Promise<string>;

export function ChooseWorkspace():Promise<main.WorkspaceInfo>;

export function CloseTerminal():Promise<void>;

export function ConfigureMCPServer(arg1:main.DesktopMCPServerInput):Promise<Array<main.DesktopMCPServer>>;

export function ConfigureOpenCode(arg1:string):Promise<void>;

export function ConfigureProvider(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateAutomation(arg1:main.AutomationInput):Promise<main.Automation>;

export function DeleteAutomation(arg1:string):Promise<void>;

export function DeleteCustomProvider(arg1:string):Promise<void>;

export function DeleteInstalledSkill(arg1:string):Promise<void>;

export function DeleteLocalMemories():Promise<main.DesktopPersonalization>;

export function DownloadUpdate(arg1:Array<main.DesktopUpdateAsset>):Promise<string>;

export function GetAccount():Promise<main.DesktopAccount>;

export function GetActiveAntigravityQuota():Promise<main.DesktopProviderQuota>;

export function GetAppInfo():Promise<main.DesktopAppInfo>;

export function GetBrowserSettings():Promise<main.DesktopBrowserSettings>;

export function GetCatalog():Promise<main.DesktopCatalog>;

export function GetKeepAwake():Promise<boolean>;

export function GetMCPServers():Promise<Array<main.DesktopMCPServer>>;

export function GetPersonalization():Promise<main.DesktopPersonalization>;

export function GetProviderSettings():Promise<main.DesktopProviderSettings>;

export function GetRemoteSession():Promise<main.DesktopRemoteSession>;

export function GetSkillsMarketplace():Promise<skills.SkillsMarketplace>;

export function GetUsageStats():Promise<main.DesktopUsageStats>;

export function GetWorkspace():Promise<main.WorkspaceInfo>;

export function InstallHeadroom():Promise<void>;

export function InstallMarketplaceSkill(arg1:string):Promise<skills.MarketplaceSkill>;

export function InstallRtk():Promise<void>;

export function InterruptTerminal():Promise<void>;

export function ListAutomations():Promise<Array<main.Automation>>;

export function ListWorkspaceTree():Promise<Array<main.FileNode>>;

export function LoginAccount():Promise<main.DesktopAccount>;

export function LoginProvider(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LogoutAccount():Promise<main.DesktopAccount>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenStandaloneChat():Promise<main.WorkspaceInfo>;

export function OpenTerminal():Promise<void>;

export function OpenUpdatePage(arg1:string):Promise<void>;

export function OpenWorkspace(arg1:string):Promise<main.WorkspaceInfo>;

export function ReadAutomationLog(arg1:string):Promise<string>;

export function ResolvePermission(arg1:string,arg2:boolean):Promise<void>;

export function RunAutomationNow(arg1:string):Promise<void>;

export function RunTerminalCommand(arg1:string):Promise<void>;

export function SaveCustomProvider(arg1:main.DesktopCustomProviderInput):Promise<main.DesktopCustomProvider>;

export function SavePersonalization(arg1:main.DesktopPersonalizationInput):Promise<main.DesktopPersonalization>;

export function SendPrompt(arg1:string):Promise<void>;

export function SetKeepAwake(arg1:boolean):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function StartRemoteSession():Promise<main.DesktopRemoteSession>;

export function SteerPrompt(arg1:string):Promise<void>;

export function StopRemoteSession():Promise<void>;

export function ToggleAutomation(arg1:string,arg2:boolean):Promise<void>;

export function UpdateAutomation(arg1:string,arg2:main.AutomationInput):Promise<main.Automation>;

export function UpdateBrowserSettings(arg1:main.DesktopBrowserSettingsInput):Promise<main.DesktopBrowserSettings>;

export function UpdateSettings(arg1:main.DesktopSettingsInput):Promise<main.DesktopSettings>;

export function UseProviderAccount(arg1:string):Promise<void>;
